// src/components/ColorCode.tsx
import useHex from "@/hooks/useHex";
import useRgb from "@/hooks/useRgb";

export default function ColorCode() {
  const { hex } = useHex(); 
  const { rgb } = useRgb();
 
  return (
    <div className="bg-slate-800/50 backdrop-blur-sm
      mt-2 p-5 rounded-md text-center">
        <p>{hex}</p>
        <p>{rgb}</p>
    </div>
  )
}

// src/components/ColorCode.vue
<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "ColorCode",
  props: {
    hex: String,
    rgb: String,
  },
});
</script>

<template>
  <div class="bg-slate-800/50 backdrop-blur-sm
  mt-2 p-5 rounded-md text-center"
  >
    <p>{{ $props.hex }}</p>
    <p>{{ $props.rgb }}</p>
  </div>
</template>
